server:
  port: 8090

spring:
  application:
    name: FGA Test

okta:
  oauth2:
    issuer: https://dev-avup2laz.us.auth0.com/
    audience: https://hello-api.okta.com
    groupsClaim: permissions


# src/main/resources/application.yaml

openfga:
  api-url: http://localhost:8080
  store-id: 01HV2KB4GCY3Z1EZMGXN55M3Y3
  authorization-model-id: 01HV2KBVPJQ9X9TCDR4DYZNCME

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


