server:
  port: 8080

spring:
  application:
    name: Document API

okta:
  oauth2:
    issuer: https://dev-avup2laz.us.auth0.com/
    audience: https://document-api.okta.com
    #groupsClaim: permissions


# src/main/resources/application.yaml

openfga:
  api-url: http://localhost:8090
  store-id: 01HVPKRS8RPMFYMSW0XQET3XPG
  authorization-model-id: 01HVPV00HA9WVVS4ZMJ3PAWA56
  initialize: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


